/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSobreRouteImport } from './routes/_site.sobre'
import { Route as SiteExperienciasRouteImport } from './routes/_site.experiencias'
import { Route as SiteEventosRouteImport } from './routes/_site.eventos'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SiteEventosSlugRouteImport } from './routes/_site.eventos.$slug'
import { Route as AuthenticatedAdminOperacaoRouteImport } from './routes/_authenticated/admin.operacao'
import { Route as AuthenticatedAdminExperienciasRouteImport } from './routes/_authenticated/admin.experiencias'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminEventosIndexRouteImport } from './routes/_authenticated/admin.eventos.index'
import { Route as AuthenticatedAdminEventosNovoRouteImport } from './routes/_authenticated/admin.eventos.novo'
import { Route as AuthenticatedAdminEventosIdIndexRouteImport } from './routes/_authenticated/admin.eventos.$id.index'
import { Route as AuthenticatedAdminEventosIdSetoresRouteImport } from './routes/_authenticated/admin.eventos.$id.setores'
import { Route as AuthenticatedAdminEventosIdReservasRouteImport } from './routes/_authenticated/admin.eventos.$id.reservas'
import { Route as AuthenticatedAdminEventosIdPromotionsRouteImport } from './routes/_authenticated/admin.eventos.$id.promotions'
import { Route as AuthenticatedAdminEventosIdPromotersRouteImport } from './routes/_authenticated/admin.eventos.$id.promoters'
import { Route as AuthenticatedAdminEventosIdLineupRouteImport } from './routes/_authenticated/admin.eventos.$id.lineup'
import { Route as AuthenticatedAdminEventosIdLeadsRouteImport } from './routes/_authenticated/admin.eventos.$id.leads'
import { Route as AuthenticatedAdminEventosIdIntelligenceRouteImport } from './routes/_authenticated/admin.eventos.$id.intelligence'
import { Route as AuthenticatedAdminEventosIdHotsiteRouteImport } from './routes/_authenticated/admin.eventos.$id.hotsite'
import { Route as AuthenticatedAdminEventosIdEspacosRouteImport } from './routes/_authenticated/admin.eventos.$id.espacos'
import { Route as AuthenticatedAdminEventosIdEntradaRouteImport } from './routes/_authenticated/admin.eventos.$id.entrada'
import { Route as AuthenticatedAdminEventosIdEngineRouteImport } from './routes/_authenticated/admin.eventos.$id.engine'
import { Route as AuthenticatedAdminEventosIdEditarRouteImport } from './routes/_authenticated/admin.eventos.$id.editar'
import { Route as AuthenticatedAdminEventosIdCredenciaisRouteImport } from './routes/_authenticated/admin.eventos.$id.credenciais'
import { Route as AuthenticatedAdminEventosIdConvitesRouteImport } from './routes/_authenticated/admin.eventos.$id.convites'
import { Route as AuthenticatedAdminEventosIdAcessoRouteImport } from './routes/_authenticated/admin.eventos.$id.acesso'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSobreRoute = SiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExperienciasRoute = SiteExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventosRoute = SiteEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SiteEventosSlugRoute = SiteEventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteEventosRoute,
} as any)
const AuthenticatedAdminOperacaoRoute =
  AuthenticatedAdminOperacaoRouteImport.update({
    id: '/operacao',
    path: '/operacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExperienciasRoute =
  AuthenticatedAdminExperienciasRouteImport.update({
    id: '/experiencias',
    path: '/experiencias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIndexRoute =
  AuthenticatedAdminEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosNovoRoute =
  AuthenticatedAdminEventosNovoRouteImport.update({
    id: '/eventos/novo',
    path: '/eventos/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdIndexRoute =
  AuthenticatedAdminEventosIdIndexRouteImport.update({
    id: '/eventos/$id/',
    path: '/eventos/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdSetoresRoute =
  AuthenticatedAdminEventosIdSetoresRouteImport.update({
    id: '/eventos/$id/setores',
    path: '/eventos/$id/setores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdReservasRoute =
  AuthenticatedAdminEventosIdReservasRouteImport.update({
    id: '/eventos/$id/reservas',
    path: '/eventos/$id/reservas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdPromotionsRoute =
  AuthenticatedAdminEventosIdPromotionsRouteImport.update({
    id: '/eventos/$id/promotions',
    path: '/eventos/$id/promotions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdPromotersRoute =
  AuthenticatedAdminEventosIdPromotersRouteImport.update({
    id: '/eventos/$id/promoters',
    path: '/eventos/$id/promoters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdLineupRoute =
  AuthenticatedAdminEventosIdLineupRouteImport.update({
    id: '/eventos/$id/lineup',
    path: '/eventos/$id/lineup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdLeadsRoute =
  AuthenticatedAdminEventosIdLeadsRouteImport.update({
    id: '/eventos/$id/leads',
    path: '/eventos/$id/leads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdIntelligenceRoute =
  AuthenticatedAdminEventosIdIntelligenceRouteImport.update({
    id: '/eventos/$id/intelligence',
    path: '/eventos/$id/intelligence',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdHotsiteRoute =
  AuthenticatedAdminEventosIdHotsiteRouteImport.update({
    id: '/eventos/$id/hotsite',
    path: '/eventos/$id/hotsite',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdEspacosRoute =
  AuthenticatedAdminEventosIdEspacosRouteImport.update({
    id: '/eventos/$id/espacos',
    path: '/eventos/$id/espacos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdEntradaRoute =
  AuthenticatedAdminEventosIdEntradaRouteImport.update({
    id: '/eventos/$id/entrada',
    path: '/eventos/$id/entrada',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdEngineRoute =
  AuthenticatedAdminEventosIdEngineRouteImport.update({
    id: '/eventos/$id/engine',
    path: '/eventos/$id/engine',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdEditarRoute =
  AuthenticatedAdminEventosIdEditarRouteImport.update({
    id: '/eventos/$id/editar',
    path: '/eventos/$id/editar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdCredenciaisRoute =
  AuthenticatedAdminEventosIdCredenciaisRouteImport.update({
    id: '/eventos/$id/credenciais',
    path: '/eventos/$id/credenciais',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdConvitesRoute =
  AuthenticatedAdminEventosIdConvitesRouteImport.update({
    id: '/eventos/$id/convites',
    path: '/eventos/$id/convites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosIdAcessoRoute =
  AuthenticatedAdminEventosIdAcessoRouteImport.update({
    id: '/eventos/$id/acesso',
    path: '/eventos/$id/acesso',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/contato': typeof SiteContatoRoute
  '/eventos': typeof SiteEventosRouteWithChildren
  '/experiencias': typeof SiteExperienciasRoute
  '/sobre': typeof SiteSobreRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/experiencias': typeof AuthenticatedAdminExperienciasRoute
  '/admin/operacao': typeof AuthenticatedAdminOperacaoRoute
  '/eventos/$slug': typeof SiteEventosSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
  '/admin/eventos/': typeof AuthenticatedAdminEventosIndexRoute
  '/admin/eventos/$id/acesso': typeof AuthenticatedAdminEventosIdAcessoRoute
  '/admin/eventos/$id/convites': typeof AuthenticatedAdminEventosIdConvitesRoute
  '/admin/eventos/$id/credenciais': typeof AuthenticatedAdminEventosIdCredenciaisRoute
  '/admin/eventos/$id/editar': typeof AuthenticatedAdminEventosIdEditarRoute
  '/admin/eventos/$id/engine': typeof AuthenticatedAdminEventosIdEngineRoute
  '/admin/eventos/$id/entrada': typeof AuthenticatedAdminEventosIdEntradaRoute
  '/admin/eventos/$id/espacos': typeof AuthenticatedAdminEventosIdEspacosRoute
  '/admin/eventos/$id/hotsite': typeof AuthenticatedAdminEventosIdHotsiteRoute
  '/admin/eventos/$id/intelligence': typeof AuthenticatedAdminEventosIdIntelligenceRoute
  '/admin/eventos/$id/leads': typeof AuthenticatedAdminEventosIdLeadsRoute
  '/admin/eventos/$id/lineup': typeof AuthenticatedAdminEventosIdLineupRoute
  '/admin/eventos/$id/promoters': typeof AuthenticatedAdminEventosIdPromotersRoute
  '/admin/eventos/$id/promotions': typeof AuthenticatedAdminEventosIdPromotionsRoute
  '/admin/eventos/$id/reservas': typeof AuthenticatedAdminEventosIdReservasRoute
  '/admin/eventos/$id/setores': typeof AuthenticatedAdminEventosIdSetoresRoute
  '/admin/eventos/$id/': typeof AuthenticatedAdminEventosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof SiteContatoRoute
  '/eventos': typeof SiteEventosRouteWithChildren
  '/experiencias': typeof SiteExperienciasRoute
  '/sobre': typeof SiteSobreRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/experiencias': typeof AuthenticatedAdminExperienciasRoute
  '/admin/operacao': typeof AuthenticatedAdminOperacaoRoute
  '/eventos/$slug': typeof SiteEventosSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosIndexRoute
  '/admin/eventos/$id/acesso': typeof AuthenticatedAdminEventosIdAcessoRoute
  '/admin/eventos/$id/convites': typeof AuthenticatedAdminEventosIdConvitesRoute
  '/admin/eventos/$id/credenciais': typeof AuthenticatedAdminEventosIdCredenciaisRoute
  '/admin/eventos/$id/editar': typeof AuthenticatedAdminEventosIdEditarRoute
  '/admin/eventos/$id/engine': typeof AuthenticatedAdminEventosIdEngineRoute
  '/admin/eventos/$id/entrada': typeof AuthenticatedAdminEventosIdEntradaRoute
  '/admin/eventos/$id/espacos': typeof AuthenticatedAdminEventosIdEspacosRoute
  '/admin/eventos/$id/hotsite': typeof AuthenticatedAdminEventosIdHotsiteRoute
  '/admin/eventos/$id/intelligence': typeof AuthenticatedAdminEventosIdIntelligenceRoute
  '/admin/eventos/$id/leads': typeof AuthenticatedAdminEventosIdLeadsRoute
  '/admin/eventos/$id/lineup': typeof AuthenticatedAdminEventosIdLineupRoute
  '/admin/eventos/$id/promoters': typeof AuthenticatedAdminEventosIdPromotersRoute
  '/admin/eventos/$id/promotions': typeof AuthenticatedAdminEventosIdPromotionsRoute
  '/admin/eventos/$id/reservas': typeof AuthenticatedAdminEventosIdReservasRoute
  '/admin/eventos/$id/setores': typeof AuthenticatedAdminEventosIdSetoresRoute
  '/admin/eventos/$id': typeof AuthenticatedAdminEventosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_site/contato': typeof SiteContatoRoute
  '/_site/eventos': typeof SiteEventosRouteWithChildren
  '/_site/experiencias': typeof SiteExperienciasRoute
  '/_site/sobre': typeof SiteSobreRoute
  '/_site/': typeof SiteIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/experiencias': typeof AuthenticatedAdminExperienciasRoute
  '/_authenticated/admin/operacao': typeof AuthenticatedAdminOperacaoRoute
  '/_site/eventos/$slug': typeof SiteEventosSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
  '/_authenticated/admin/eventos/': typeof AuthenticatedAdminEventosIndexRoute
  '/_authenticated/admin/eventos/$id/acesso': typeof AuthenticatedAdminEventosIdAcessoRoute
  '/_authenticated/admin/eventos/$id/convites': typeof AuthenticatedAdminEventosIdConvitesRoute
  '/_authenticated/admin/eventos/$id/credenciais': typeof AuthenticatedAdminEventosIdCredenciaisRoute
  '/_authenticated/admin/eventos/$id/editar': typeof AuthenticatedAdminEventosIdEditarRoute
  '/_authenticated/admin/eventos/$id/engine': typeof AuthenticatedAdminEventosIdEngineRoute
  '/_authenticated/admin/eventos/$id/entrada': typeof AuthenticatedAdminEventosIdEntradaRoute
  '/_authenticated/admin/eventos/$id/espacos': typeof AuthenticatedAdminEventosIdEspacosRoute
  '/_authenticated/admin/eventos/$id/hotsite': typeof AuthenticatedAdminEventosIdHotsiteRoute
  '/_authenticated/admin/eventos/$id/intelligence': typeof AuthenticatedAdminEventosIdIntelligenceRoute
  '/_authenticated/admin/eventos/$id/leads': typeof AuthenticatedAdminEventosIdLeadsRoute
  '/_authenticated/admin/eventos/$id/lineup': typeof AuthenticatedAdminEventosIdLineupRoute
  '/_authenticated/admin/eventos/$id/promoters': typeof AuthenticatedAdminEventosIdPromotersRoute
  '/_authenticated/admin/eventos/$id/promotions': typeof AuthenticatedAdminEventosIdPromotionsRoute
  '/_authenticated/admin/eventos/$id/reservas': typeof AuthenticatedAdminEventosIdReservasRoute
  '/_authenticated/admin/eventos/$id/setores': typeof AuthenticatedAdminEventosIdSetoresRoute
  '/_authenticated/admin/eventos/$id/': typeof AuthenticatedAdminEventosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/contato'
    | '/eventos'
    | '/experiencias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/experiencias'
    | '/admin/operacao'
    | '/eventos/$slug'
    | '/admin/'
    | '/admin/eventos/novo'
    | '/admin/eventos/'
    | '/admin/eventos/$id/acesso'
    | '/admin/eventos/$id/convites'
    | '/admin/eventos/$id/credenciais'
    | '/admin/eventos/$id/editar'
    | '/admin/eventos/$id/engine'
    | '/admin/eventos/$id/entrada'
    | '/admin/eventos/$id/espacos'
    | '/admin/eventos/$id/hotsite'
    | '/admin/eventos/$id/intelligence'
    | '/admin/eventos/$id/leads'
    | '/admin/eventos/$id/lineup'
    | '/admin/eventos/$id/promoters'
    | '/admin/eventos/$id/promotions'
    | '/admin/eventos/$id/reservas'
    | '/admin/eventos/$id/setores'
    | '/admin/eventos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/eventos'
    | '/experiencias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/experiencias'
    | '/admin/operacao'
    | '/eventos/$slug'
    | '/admin'
    | '/admin/eventos/novo'
    | '/admin/eventos'
    | '/admin/eventos/$id/acesso'
    | '/admin/eventos/$id/convites'
    | '/admin/eventos/$id/credenciais'
    | '/admin/eventos/$id/editar'
    | '/admin/eventos/$id/engine'
    | '/admin/eventos/$id/entrada'
    | '/admin/eventos/$id/espacos'
    | '/admin/eventos/$id/hotsite'
    | '/admin/eventos/$id/intelligence'
    | '/admin/eventos/$id/leads'
    | '/admin/eventos/$id/lineup'
    | '/admin/eventos/$id/promoters'
    | '/admin/eventos/$id/promotions'
    | '/admin/eventos/$id/reservas'
    | '/admin/eventos/$id/setores'
    | '/admin/eventos/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/_authenticated/admin'
    | '/_site/contato'
    | '/_site/eventos'
    | '/_site/experiencias'
    | '/_site/sobre'
    | '/_site/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/experiencias'
    | '/_authenticated/admin/operacao'
    | '/_site/eventos/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/eventos/novo'
    | '/_authenticated/admin/eventos/'
    | '/_authenticated/admin/eventos/$id/acesso'
    | '/_authenticated/admin/eventos/$id/convites'
    | '/_authenticated/admin/eventos/$id/credenciais'
    | '/_authenticated/admin/eventos/$id/editar'
    | '/_authenticated/admin/eventos/$id/engine'
    | '/_authenticated/admin/eventos/$id/entrada'
    | '/_authenticated/admin/eventos/$id/espacos'
    | '/_authenticated/admin/eventos/$id/hotsite'
    | '/_authenticated/admin/eventos/$id/intelligence'
    | '/_authenticated/admin/eventos/$id/leads'
    | '/_authenticated/admin/eventos/$id/lineup'
    | '/_authenticated/admin/eventos/$id/promoters'
    | '/_authenticated/admin/eventos/$id/promotions'
    | '/_authenticated/admin/eventos/$id/reservas'
    | '/_authenticated/admin/eventos/$id/setores'
    | '/_authenticated/admin/eventos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sobre': {
      id: '/_site/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SiteSobreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/experiencias': {
      id: '/_site/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof SiteExperienciasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/eventos': {
      id: '/_site/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof SiteEventosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_site/eventos/$slug': {
      id: '/_site/eventos/$slug'
      path: '/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof SiteEventosSlugRouteImport
      parentRoute: typeof SiteEventosRoute
    }
    '/_authenticated/admin/operacao': {
      id: '/_authenticated/admin/operacao'
      path: '/operacao'
      fullPath: '/admin/operacao'
      preLoaderRoute: typeof AuthenticatedAdminOperacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/experiencias': {
      id: '/_authenticated/admin/experiencias'
      path: '/experiencias'
      fullPath: '/admin/experiencias'
      preLoaderRoute: typeof AuthenticatedAdminExperienciasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/': {
      id: '/_authenticated/admin/eventos/'
      path: '/eventos'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AuthenticatedAdminEventosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/novo': {
      id: '/_authenticated/admin/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/admin/eventos/novo'
      preLoaderRoute: typeof AuthenticatedAdminEventosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/': {
      id: '/_authenticated/admin/eventos/$id/'
      path: '/eventos/$id'
      fullPath: '/admin/eventos/$id/'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/setores': {
      id: '/_authenticated/admin/eventos/$id/setores'
      path: '/eventos/$id/setores'
      fullPath: '/admin/eventos/$id/setores'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdSetoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/reservas': {
      id: '/_authenticated/admin/eventos/$id/reservas'
      path: '/eventos/$id/reservas'
      fullPath: '/admin/eventos/$id/reservas'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdReservasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/promotions': {
      id: '/_authenticated/admin/eventos/$id/promotions'
      path: '/eventos/$id/promotions'
      fullPath: '/admin/eventos/$id/promotions'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/promoters': {
      id: '/_authenticated/admin/eventos/$id/promoters'
      path: '/eventos/$id/promoters'
      fullPath: '/admin/eventos/$id/promoters'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdPromotersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/lineup': {
      id: '/_authenticated/admin/eventos/$id/lineup'
      path: '/eventos/$id/lineup'
      fullPath: '/admin/eventos/$id/lineup'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdLineupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/leads': {
      id: '/_authenticated/admin/eventos/$id/leads'
      path: '/eventos/$id/leads'
      fullPath: '/admin/eventos/$id/leads'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/intelligence': {
      id: '/_authenticated/admin/eventos/$id/intelligence'
      path: '/eventos/$id/intelligence'
      fullPath: '/admin/eventos/$id/intelligence'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/hotsite': {
      id: '/_authenticated/admin/eventos/$id/hotsite'
      path: '/eventos/$id/hotsite'
      fullPath: '/admin/eventos/$id/hotsite'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdHotsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/espacos': {
      id: '/_authenticated/admin/eventos/$id/espacos'
      path: '/eventos/$id/espacos'
      fullPath: '/admin/eventos/$id/espacos'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdEspacosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/entrada': {
      id: '/_authenticated/admin/eventos/$id/entrada'
      path: '/eventos/$id/entrada'
      fullPath: '/admin/eventos/$id/entrada'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdEntradaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/engine': {
      id: '/_authenticated/admin/eventos/$id/engine'
      path: '/eventos/$id/engine'
      fullPath: '/admin/eventos/$id/engine'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdEngineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/editar': {
      id: '/_authenticated/admin/eventos/$id/editar'
      path: '/eventos/$id/editar'
      fullPath: '/admin/eventos/$id/editar'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdEditarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/credenciais': {
      id: '/_authenticated/admin/eventos/$id/credenciais'
      path: '/eventos/$id/credenciais'
      fullPath: '/admin/eventos/$id/credenciais'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdCredenciaisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/convites': {
      id: '/_authenticated/admin/eventos/$id/convites'
      path: '/eventos/$id/convites'
      fullPath: '/admin/eventos/$id/convites'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdConvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/$id/acesso': {
      id: '/_authenticated/admin/eventos/$id/acesso'
      path: '/eventos/$id/acesso'
      fullPath: '/admin/eventos/$id/acesso'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdAcessoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminExperienciasRoute: typeof AuthenticatedAdminExperienciasRoute
  AuthenticatedAdminOperacaoRoute: typeof AuthenticatedAdminOperacaoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventosNovoRoute: typeof AuthenticatedAdminEventosNovoRoute
  AuthenticatedAdminEventosIndexRoute: typeof AuthenticatedAdminEventosIndexRoute
  AuthenticatedAdminEventosIdAcessoRoute: typeof AuthenticatedAdminEventosIdAcessoRoute
  AuthenticatedAdminEventosIdConvitesRoute: typeof AuthenticatedAdminEventosIdConvitesRoute
  AuthenticatedAdminEventosIdCredenciaisRoute: typeof AuthenticatedAdminEventosIdCredenciaisRoute
  AuthenticatedAdminEventosIdEditarRoute: typeof AuthenticatedAdminEventosIdEditarRoute
  AuthenticatedAdminEventosIdEngineRoute: typeof AuthenticatedAdminEventosIdEngineRoute
  AuthenticatedAdminEventosIdEntradaRoute: typeof AuthenticatedAdminEventosIdEntradaRoute
  AuthenticatedAdminEventosIdEspacosRoute: typeof AuthenticatedAdminEventosIdEspacosRoute
  AuthenticatedAdminEventosIdHotsiteRoute: typeof AuthenticatedAdminEventosIdHotsiteRoute
  AuthenticatedAdminEventosIdIntelligenceRoute: typeof AuthenticatedAdminEventosIdIntelligenceRoute
  AuthenticatedAdminEventosIdLeadsRoute: typeof AuthenticatedAdminEventosIdLeadsRoute
  AuthenticatedAdminEventosIdLineupRoute: typeof AuthenticatedAdminEventosIdLineupRoute
  AuthenticatedAdminEventosIdPromotersRoute: typeof AuthenticatedAdminEventosIdPromotersRoute
  AuthenticatedAdminEventosIdPromotionsRoute: typeof AuthenticatedAdminEventosIdPromotionsRoute
  AuthenticatedAdminEventosIdReservasRoute: typeof AuthenticatedAdminEventosIdReservasRoute
  AuthenticatedAdminEventosIdSetoresRoute: typeof AuthenticatedAdminEventosIdSetoresRoute
  AuthenticatedAdminEventosIdIndexRoute: typeof AuthenticatedAdminEventosIdIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminExperienciasRoute: AuthenticatedAdminExperienciasRoute,
  AuthenticatedAdminOperacaoRoute: AuthenticatedAdminOperacaoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventosNovoRoute: AuthenticatedAdminEventosNovoRoute,
  AuthenticatedAdminEventosIndexRoute: AuthenticatedAdminEventosIndexRoute,
  AuthenticatedAdminEventosIdAcessoRoute:
    AuthenticatedAdminEventosIdAcessoRoute,
  AuthenticatedAdminEventosIdConvitesRoute:
    AuthenticatedAdminEventosIdConvitesRoute,
  AuthenticatedAdminEventosIdCredenciaisRoute:
    AuthenticatedAdminEventosIdCredenciaisRoute,
  AuthenticatedAdminEventosIdEditarRoute:
    AuthenticatedAdminEventosIdEditarRoute,
  AuthenticatedAdminEventosIdEngineRoute:
    AuthenticatedAdminEventosIdEngineRoute,
  AuthenticatedAdminEventosIdEntradaRoute:
    AuthenticatedAdminEventosIdEntradaRoute,
  AuthenticatedAdminEventosIdEspacosRoute:
    AuthenticatedAdminEventosIdEspacosRoute,
  AuthenticatedAdminEventosIdHotsiteRoute:
    AuthenticatedAdminEventosIdHotsiteRoute,
  AuthenticatedAdminEventosIdIntelligenceRoute:
    AuthenticatedAdminEventosIdIntelligenceRoute,
  AuthenticatedAdminEventosIdLeadsRoute: AuthenticatedAdminEventosIdLeadsRoute,
  AuthenticatedAdminEventosIdLineupRoute:
    AuthenticatedAdminEventosIdLineupRoute,
  AuthenticatedAdminEventosIdPromotersRoute:
    AuthenticatedAdminEventosIdPromotersRoute,
  AuthenticatedAdminEventosIdPromotionsRoute:
    AuthenticatedAdminEventosIdPromotionsRoute,
  AuthenticatedAdminEventosIdReservasRoute:
    AuthenticatedAdminEventosIdReservasRoute,
  AuthenticatedAdminEventosIdSetoresRoute:
    AuthenticatedAdminEventosIdSetoresRoute,
  AuthenticatedAdminEventosIdIndexRoute: AuthenticatedAdminEventosIdIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteEventosRouteChildren {
  SiteEventosSlugRoute: typeof SiteEventosSlugRoute
}

const SiteEventosRouteChildren: SiteEventosRouteChildren = {
  SiteEventosSlugRoute: SiteEventosSlugRoute,
}

const SiteEventosRouteWithChildren = SiteEventosRoute._addFileChildren(
  SiteEventosRouteChildren,
)

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteEventosRoute: typeof SiteEventosRouteWithChildren
  SiteExperienciasRoute: typeof SiteExperienciasRoute
  SiteSobreRoute: typeof SiteSobreRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteEventosRoute: SiteEventosRouteWithChildren,
  SiteExperienciasRoute: SiteExperienciasRoute,
  SiteSobreRoute: SiteSobreRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
