/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSobreRouteImport } from './routes/_site.sobre'
import { Route as SiteExperienciasRouteImport } from './routes/_site.experiencias'
import { Route as SiteEventosRouteImport } from './routes/_site.eventos'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SiteEventosSlugRouteImport } from './routes/_site.eventos.$slug'
import { Route as AuthenticatedAdminOperacaoRouteImport } from './routes/_authenticated/admin.operacao'
import { Route as AuthenticatedAdminExperienciasRouteImport } from './routes/_authenticated/admin.experiencias'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminEventosNovoRouteImport } from './routes/_authenticated/admin.eventos.novo'
import { Route as AuthenticatedAdminEventosIdRouteImport } from './routes/_authenticated/admin.eventos.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSobreRoute = SiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExperienciasRoute = SiteExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventosRoute = SiteEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SiteEventosSlugRoute = SiteEventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteEventosRoute,
} as any)
const AuthenticatedAdminOperacaoRoute =
  AuthenticatedAdminOperacaoRouteImport.update({
    id: '/operacao',
    path: '/operacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExperienciasRoute =
  AuthenticatedAdminExperienciasRouteImport.update({
    id: '/experiencias',
    path: '/experiencias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosNovoRoute =
  AuthenticatedAdminEventosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminEventosRoute,
  } as any)
const AuthenticatedAdminEventosIdRoute =
  AuthenticatedAdminEventosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEventosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/contato': typeof SiteContatoRoute
  '/eventos': typeof SiteEventosRouteWithChildren
  '/experiencias': typeof SiteExperienciasRoute
  '/sobre': typeof SiteSobreRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRouteWithChildren
  '/admin/experiencias': typeof AuthenticatedAdminExperienciasRoute
  '/admin/operacao': typeof AuthenticatedAdminOperacaoRoute
  '/eventos/$slug': typeof SiteEventosSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/eventos/$id': typeof AuthenticatedAdminEventosIdRoute
  '/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof SiteContatoRoute
  '/eventos': typeof SiteEventosRouteWithChildren
  '/experiencias': typeof SiteExperienciasRoute
  '/sobre': typeof SiteSobreRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRouteWithChildren
  '/admin/experiencias': typeof AuthenticatedAdminExperienciasRoute
  '/admin/operacao': typeof AuthenticatedAdminOperacaoRoute
  '/eventos/$slug': typeof SiteEventosSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/eventos/$id': typeof AuthenticatedAdminEventosIdRoute
  '/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_site/contato': typeof SiteContatoRoute
  '/_site/eventos': typeof SiteEventosRouteWithChildren
  '/_site/experiencias': typeof SiteExperienciasRoute
  '/_site/sobre': typeof SiteSobreRoute
  '/_site/': typeof SiteIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRouteWithChildren
  '/_authenticated/admin/experiencias': typeof AuthenticatedAdminExperienciasRoute
  '/_authenticated/admin/operacao': typeof AuthenticatedAdminOperacaoRoute
  '/_site/eventos/$slug': typeof SiteEventosSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/eventos/$id': typeof AuthenticatedAdminEventosIdRoute
  '/_authenticated/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/contato'
    | '/eventos'
    | '/experiencias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/experiencias'
    | '/admin/operacao'
    | '/eventos/$slug'
    | '/admin/'
    | '/admin/eventos/$id'
    | '/admin/eventos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/eventos'
    | '/experiencias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/experiencias'
    | '/admin/operacao'
    | '/eventos/$slug'
    | '/admin'
    | '/admin/eventos/$id'
    | '/admin/eventos/novo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/_authenticated/admin'
    | '/_site/contato'
    | '/_site/eventos'
    | '/_site/experiencias'
    | '/_site/sobre'
    | '/_site/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/experiencias'
    | '/_authenticated/admin/operacao'
    | '/_site/eventos/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/eventos/$id'
    | '/_authenticated/admin/eventos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sobre': {
      id: '/_site/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SiteSobreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/experiencias': {
      id: '/_site/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof SiteExperienciasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/eventos': {
      id: '/_site/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof SiteEventosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_site/eventos/$slug': {
      id: '/_site/eventos/$slug'
      path: '/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof SiteEventosSlugRouteImport
      parentRoute: typeof SiteEventosRoute
    }
    '/_authenticated/admin/operacao': {
      id: '/_authenticated/admin/operacao'
      path: '/operacao'
      fullPath: '/admin/operacao'
      preLoaderRoute: typeof AuthenticatedAdminOperacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/experiencias': {
      id: '/_authenticated/admin/experiencias'
      path: '/experiencias'
      fullPath: '/admin/experiencias'
      preLoaderRoute: typeof AuthenticatedAdminExperienciasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos/novo': {
      id: '/_authenticated/admin/eventos/novo'
      path: '/novo'
      fullPath: '/admin/eventos/novo'
      preLoaderRoute: typeof AuthenticatedAdminEventosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminEventosRoute
    }
    '/_authenticated/admin/eventos/$id': {
      id: '/_authenticated/admin/eventos/$id'
      path: '/$id'
      fullPath: '/admin/eventos/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventosIdRouteImport
      parentRoute: typeof AuthenticatedAdminEventosRoute
    }
  }
}

interface AuthenticatedAdminEventosRouteChildren {
  AuthenticatedAdminEventosIdRoute: typeof AuthenticatedAdminEventosIdRoute
  AuthenticatedAdminEventosNovoRoute: typeof AuthenticatedAdminEventosNovoRoute
}

const AuthenticatedAdminEventosRouteChildren: AuthenticatedAdminEventosRouteChildren =
  {
    AuthenticatedAdminEventosIdRoute: AuthenticatedAdminEventosIdRoute,
    AuthenticatedAdminEventosNovoRoute: AuthenticatedAdminEventosNovoRoute,
  }

const AuthenticatedAdminEventosRouteWithChildren =
  AuthenticatedAdminEventosRoute._addFileChildren(
    AuthenticatedAdminEventosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRouteWithChildren
  AuthenticatedAdminExperienciasRoute: typeof AuthenticatedAdminExperienciasRoute
  AuthenticatedAdminOperacaoRoute: typeof AuthenticatedAdminOperacaoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRouteWithChildren,
  AuthenticatedAdminExperienciasRoute: AuthenticatedAdminExperienciasRoute,
  AuthenticatedAdminOperacaoRoute: AuthenticatedAdminOperacaoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteEventosRouteChildren {
  SiteEventosSlugRoute: typeof SiteEventosSlugRoute
}

const SiteEventosRouteChildren: SiteEventosRouteChildren = {
  SiteEventosSlugRoute: SiteEventosSlugRoute,
}

const SiteEventosRouteWithChildren = SiteEventosRoute._addFileChildren(
  SiteEventosRouteChildren,
)

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteEventosRoute: typeof SiteEventosRouteWithChildren
  SiteExperienciasRoute: typeof SiteExperienciasRoute
  SiteSobreRoute: typeof SiteSobreRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteEventosRoute: SiteEventosRouteWithChildren,
  SiteExperienciasRoute: SiteExperienciasRoute,
  SiteSobreRoute: SiteSobreRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
